In `+Terminal 2+`, exec into the running container and start a bash
shell

[source,bash,run]
----
podman exec -t -i $CONTAINER /bin/bash
----

Check whether container has access to the _/home_ directory

[source,bash,run]
----
cd /home/; ls
----

This is now successful since there is an allow rule in place that tells
SELinux to allow this action.

Check whether container has read access to the _/var/spool/_ directory

[source,bash,run]
----
cd /var/spool/; ls
----

Similarly, this is also successful because there is an allow rule in
place that tells SELinux to allow this action.

Check whether container has write access to the /var/spool/ directory

[source,bash,run]
----
touch test; ls
----

Install the netcat (nc) package inside the container to test for port
bindings

[source,bash,run]
----
dnf install -y nc
----

Tell nc to listen on port 80 inside the container, and timeout after 5
seconds.

[source,bash,run]
----
timeout 5s nc -lvvp 80
----

You can see from the above output that netcat was able to connect and
listen on port 80. This is successful because there is a allow rule in
place that tells SELinux to allow this network action on port 80.

Tell nc to listen on port 8080 inside the container, and timeout after 5
seconds.

[source,bash,run]
----
timeout 5s nc -lvvp 8080
----

You can see from the above output that netcat was NOT able to connect
and listen on port 8080. There is no allow rule in place that tells
SELinux to allow this operation, and hence it was blocked by SELinux.
