---
virtualmachines:
  - name: "rhel"
    image: "rhel-10-0-07-09-25-3"
    packages:
      - buildah
      - podman
      - git
      - httpd
      - tmux
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
